### DISCUSSION TITLE
Proper use of sql alchemy / How sql alchemy interacts with a db

### DISCUSSION THREAD

**Discussion by ben-vega** [sqlalchemy/sqlalchemy#10252] [Usage Questions]
Hi, first off thanks for your time reading this. I am confused on how exactly SQL alchemy interacts with a database with regards to holding open connections, database locks, and management of db resources. I have a fairly large codebase where sqlalchemy is used as an ORM(most of the time) to interact with the tables in a Aurora postgres 15.2 database that is hosted in aws rds. this is in a fastapi app. I have provided examples of what I think are all the pieces that are needed, but there is much more in the whole codebase that I have not included for brevity, so if more context is needed I can provide it.

I am experiencing an issue where a certain query is locking up the database, the database tells me this is the problematic query. code context for the query is provided below:
```sql
SELECT * FROM table WHERE column1 = '{param}' AND status = 1 AND created_at >= NOW() - INTERVAL '30 minutes'
```
```python
from sqlalchemy.ext.asyncio import (
    async_scoped_session,
    async_sessionmaker,
    create_async_engine,
    AsyncSession,
)
from sqlalchemy.ext.asyncio import AsyncSession
from starlette.requests import Request
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession
from asyncio import current_task
from fastapi import Depends
from typing import AsyncGenerator


def create_db_session() -> AsyncSession:  # pragma: no cover
    """
    Creates new connection to the database.

    This function creates SQLAlchemy engine instance,
    session_factory for creating sessions
    and stores them in the application's state property.

    :param app: fastAPI application.
    """
    engine = create_async_engine(str(settings.db_url), echo=settings.db_echo)
    session_factory = async_scoped_session(
        async_sessionmaker(
            engine,
            expire_on_commit=False,
        ),
        scopefunc=current_task,
    )

    session: AsyncSession = session_factory()
    return session

async def get_db_session(request: Request) -> AsyncGenerator[AsyncSession, None]:
    """
    Create and get database session.

    :param request: current request.
    :yield: database session.
    """
    session: AsyncSession = request.app.state.db_session_factory()

    try:  # noqa: WPS501
        yield session
    finally:
        await session.commit()
        await session.close()

class ResultsDAO:
    """Class for accessing dummy table."""

    def __init__(self, session: AsyncSession = Depends(get_db_session)):
        self.session = session

    async def get_requested_in_last_30_minutes(self, param: str):
        sql = f"SELECT * FROM table WHERE column1 = '{param}' AND status = 1 AND created_at >= NOW() - INTERVAL '30 minutes'"
        raw_request = await self.session.execute(text(sql))
        result = raw_request.fetchall()
        self.session.commit()
        if not result:
            return None

        request_id = result[0][0]
        request_datetime = result[0][3]
        self.session.commit()
        cooldown_time_remaining = get_cooldown_time(request_datetime)
        print(f"cooldown_time_remaining: {cooldown_time_remaining}")
        return dict(
            request_id=request_id,
            param=param,
            request_datetime=request_datetime,
            cooldown_time_remaining=cooldown_time_remaining,
        )
```

pyproject.toml:
```toml
[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.98.0"
uvicorn = { version = "^0.22.0", extras = ["standard"] }
pydantic = {version = "^1.10.4", extras = ["dotenv"]}
yarl = "^1.8.2"
ujson = "^5.7.0"
SQLAlchemy = {extras = ["mypy"], version = "^2.0.16"}
asyncpg = {version = "^0.27.0", extras = ["sa"]}
aiofiles = "^23.1.0"
httptools = "^0.5.0"
prometheus-client = "^0.17.0"
prometheus-fastapi-instrumentator = "5.9.1"
loguru = "^0.7.0"
psycopg-binary = "^3.1.8"
psycopg = "^3.1.8"
python-dotenv = "^1.0.0"
crypto = "^1.4.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
natsort = "^8.3.1"
python-multipart = "^0.0.6"
ruff = "^0.0.275"
black = "^23.3.0"
types-urllib3 = "^1.26.25.13"
types-requests = "^2.31.0.1"
websockets = "^11.0.3"
greenlet = "^2.0.2"
distlib = "^0.3.7"
fastapi-pagination = "^0.12.6"
pytz = "^2023.3"
```
Is it the failure to await the session.commits()? I thought that the create_db_session() was supposed to close it after the dao goes out of scope. Does this code properly release the lock on the db? is there scenarios where this code might have problems? any advice is appreciated :)
