### DISCUSSION TITLE
aiomysql causes an Aborted Client

### DISCUSSION THREAD

**Discussion by mmingyu** [sqlalchemy/sqlalchemy#12259] [Usage Questions] [answered]
It seems that the `terminate` method in [dialects/mysql/aiomysql.py AsyncAdapt_aiomysql_connection](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/mysql/aiomysql.py#L73) is causing a [MySQL "Aborted Client" issue](https://github.com/aio-libs/aiomysql/discussions/990) by calling `close()` instead of `ensure_closed()`.

```
    def terminate(self):
        # it's not awaitable.
        self._connection.close()
```

Is there a specific reason for the comment saying, "it's not awaitable"?
I believe this should be updated to `await self._connection.ensure_closed()` to resolve the issue.

**Comment by CaselIT** [comment, marked as answer]
Hi,

That method is used to terminate a connection, ensure closed is called by the normal close method.
When is this causing issues?

**Reply by mmingyu** [reply]
I think aborted clients occur each time a connection is recycled in the pool and terminate connection.

https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/pool/base.py#L863

**Reply by mmingyu** [reply]
The connection in aiomysql must be closed using `ensure_closed`.

**Reply by mmingyu** [reply]
## Reproduce Code
`test.py`
```python
import asyncio

from sqlalchemy import text
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

engine = create_async_engine(
    url='mysql+aiomysql://root:1111@127.0.0.1:3306',
    pool_pre_ping=True,
    pool_size=1,
    max_overflow=1,
    pool_recycle=3,  # recycle connection every 3 seconds
    pool_reset_on_return=None,
    isolation_level='AUTOCOMMIT',
)

sessionmaker = async_sessionmaker(autoflush=True, bind=engine)


async def test():
    async def check_error_log():
        async with sessionmaker() as session:
            result = await session.execute(text('SELECT * FROM performance_schema.error_log order by LOGGED desc limit 1'))
            print(result.fetchall())

    async with sessionmaker() as session:
        result = await session.execute(text('SELECT 1'))
        print(result.fetchall())

    print('Before 15 seconds')
    await check_error_log()

    await asyncio.sleep(15)

    print('After 15 seconds')
    await check_error_log()
    await engine.dispose()


asyncio.run(test())
```

`docker-compose.yml`
```
services:
    reco-mysql:
        image: mysql:latest
        container_name: reco-mysql
        environment:
            MYSQL_ROOT_PASSWORD: "1111"
        volumes:
            - /var/lib/mysql:/var/lib/mysql
            - /var/run/mysqld:/var/run/mysqld
        ports:
            - "3306:3306"
        command: --log_error_verbosity=3
```

## Output
```
[(1,)]
Before 15 seconds
[(datetime.datetime(2025, 1, 22, 0, 50, 19, 997003), 0, 'System', 'MY-010931', 'Server', "/usr/sbin/mysqld: ready for connections. Version: '9.1.0'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.")]
After 15 seconds
[(datetime.datetime(2025, 1, 22, 0, 50, 45, 464821), 8, 'Note', 'MY-010914', 'Server', "Aborted connection 8 to db: 'unconnected' user: 'root' host: '172.18.0.1' (Got an error reading communication packets).")]
```
Recycled connections cause aborted connection errors. In the Ubuntu 22.04 environment, it triggers an `Aborted connection` error, while in Aurora MySQL, it appears to cause an `Aborted Client` error.
