### ISSUE TITLE
Missing css file in https://docs.sqlalchemy.org/14/sqlalchemy_14.zip file

### ISSUE THREAD

**Issue by honglei** [sqlalchemy/sqlalchemy#5727]
The missed css file caused load page very slow when using document offline. 
_static/docs.css file:
```css
@import url(https://fonts.googleapis.com/css?family=Oxygen|Libre+Franklin:400,700);
.body-background {
  background-color: #FDFBFC;
}
```
